Avengers = []
Avengers.append("Captain America")
Avengers.append("Iron Man")
Avengers.append("Black Widow")
Avengers.append("Spider-man")
Avengers.append("Hulk")
Avengers.append("Doctor Strange")
Avengers.append("Hawkeye")
Avengers.append("Scarlet Witch")
Avengers.append("Black Panther")
Avengers.append("Falcon")
Avengers.append("War Machine")
Avengers.append("Vision")
print(Avengers)
print(sorted(Avengers))
